name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up UV
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: uv pip install pytest

    - name: Run tests
      run: uv run pytest